export const popupImage = document.querySelector('#popup-image')
export const figureImage = document.querySelector('.popup__image')
export const imageCaption = document.querySelector('.popup__image-caption')

export const popupProfile = document.querySelector('#popup-profile')
export const formProfileElement = document.querySelector('#popup__form-profile')
export const nameInput = document.querySelector('#popup__field_type_name-profile')
export const aboutInput = document.querySelector('#popup__field_type_about-profile')
export const profileName = document.querySelector('.profile__name')
export const profileAbout = document.querySelector('.profile__about')
export const editProfileButton = document.querySelector('.profile__edit-button')
export const popupAddCards = document.querySelector('#popup-add-cards')
export const formAddCardsElement = document.querySelector('#popup__form-add-cards')
export const nameInputAddCards = document.querySelector('#popup__field_type_name-add-cards')
export const linkInputAddCards = document.querySelector('#popup__field_type_link-add-cards')
export const addCardsButton = document.querySelector('.profile__add-button')
export const popupList = Array.from(document.querySelectorAll('.popup'))
export const cardListSection = document.querySelector('.cards')
